Use master
--drop database QUANLYBANVEMAYBAY
CREATE DATABASE QUANLYBANVEMAYBAY
GO

USE QUANLYBANVEMAYBAY
GO

--TAI KHOAN
--CHUYEN BAY
--VE BAN
--THONG TIN VE 

CREATE TABLE TAIKHOAN
(
	TENTK		NVARCHAR(100)		NOT NULL,
	MATKHAU		NVARCHAR(100)		NOT NULL,
	
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(TENTK)
)
GO

CREATE TABLE CHUYENBAY
(
	MACB	INT IDENTITY(1,1)	NOT NULL,
	TENCB	Nvarchar(1000)		not null,

	CONSTRAINT PK_CHUYENBAY PRIMARY KEY(MACB),
)
GO


CREATE TABLE VEBAN
(
	MAVEBAN	INT IDENTITY(1,1)	NOT NULL,
	MACB	INT					NOT NULL,
	DITUDEN	NVARCHAR(1000)		NOT NULL,
	GIA		FLOAT				NOT NULL DEFAULT 0,

	CONSTRAINT PK_VEBAN PRIMARY KEY(MAVEBAN),
	CONSTRAINT FK_CHUYENBAY	FOREIGN KEY(MACB) REFERENCES CHUYENBAY(MACB),
)
GO

CREATE TABLE THONGTINCHITIETVE
(
	MAVE	INT IDENTITY(1,1)	NOT NULL,
	MAVEBAN	INT					NOT NULL,
	DITUDEN	Nvarchar(1000)		NOT NULL,
	SOLUONG	INT					NOT NULL,
	TONG	FLOAT				NOT NULL DEFAULT 0,

	CONSTRAINT PK_THONGTINCHITIETVE PRIMARY KEY(MAVE),
	CONSTRAINT FK_VEBAN		FOREIGN KEY(MAVEBAN) REFERENCES VEBAN(MAVEBAN),

)
GO

CREATE PROC USP_GetAccountByUserName
@tenTK nvarchar(100)
AS
BEGIN
	SELECT * FROM TAIKHOAN WHERE TENTK = @tenTK
END
GO
Exec USP_GetAccountByUserName @tenTK =N'ducduy'--nvarchar(100)
SELECT * FROM dbo.TAIKHOAN WHERE TENTK = N'ducduy' AND MATKHAU = N'123'

go
--Them chuyen bay
INSERT INTO CHUYENBAY VALUES(N'TRONG NƯỚC')
INSERT INTO CHUYENBAY VALUES(N'CHÂU Á')
INSERT INTO CHUYENBAY VALUES(N'CHÂU ÂU')
INSERT INTO CHUYENBAY VALUES(N'CHÂU MĨ')


go
--Tai khoan
INSERT INTO TAIKHOAN VALUES(N'ducduy',N'123')

--Them ve ban
INSERT INTO VEBAN VALUES(1,N' THÀNH PHỐ HỒ CHÍ MINH - HÀ NỘI',950000)
INSERT INTO VEBAN VALUES(1,N' PHÚ QUỐC - HÀ NỘI',1070000)
INSERT INTO VEBAN VALUES(1,N' ĐÀ LẠT - CẦN THƠ',200000)
INSERT INTO VEBAN VALUES(2,N' HÀ NỘI - NHẬT BẢN',1500000)
INSERT INTO VEBAN VALUES(2,N' THÀNH PHỐ HỒ CHÍ MINH - TRUNG QUỐC',3500000)
INSERT INTO VEBAN VALUES(3,N' ĐÀ NẴNG - PHÁP',2000000)
INSERT INTO VEBAN VALUES(3,N' THÀNH PHÔ HÔ CHÍ MINH - ĐỨC',2050000)
INSERT INTO VEBAN VALUES(4,N' NHA TRANG - MỸ',3500000)

--Them thong tin chi tiet ve ban
INSERT INTO THONGTINCHITIETVE VALUES(1,N' THÀNH PHỐ HỒ CHÍ MINH - HÀ NỘI',2,1900000)
INSERT INTO THONGTINCHITIETVE VALUES(5,N' THÀNH PHỐ HỒ CHÍ MINH - TRUNG QUỐC',1,3500000)
INSERT INTO THONGTINCHITIETVE VALUES(3,N' ĐÀ LẠT - CẦN THƠ',2,400000)
INSERT INTO THONGTINCHITIETVE VALUES(8,N' NHA TRANG - MỸ',1,3500000)
INSERT INTO THONGTINCHITIETVE VALUES(7,N' THÀNH PHÔ HÔ CHÍ MINH - ĐỨC',3,6150000)

----------------------------------
select * from CHUYENBAY
select * from VEBAN
select * from THONGTINCHITIETVE
Insert VEBAN(MACB, DITUDEN, GIA) Values (1,N' ĐÀ NẴNG - QUẢNG NGÃI',11000)
UPDATE VEBAN SET MACB = 1, DITUDEN = N'QUẢNG NGÃI - NHA TRANG', GIA = 150000 WHERE MAVEBAN = 10
Insert CHUYENBAY(TENCB) Values (N'ĐÔNG ÂU')